[project]
name = "lbm"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.*"
dependencies = [
    "imageio>=2.37.2",
    "matplotlib>=3.10.8",
    "pillow>=12.0.0",
    "xlb>=0.3.0",
]

[project.optional-dependencies]
cuda = [
    "xlb[cuda]>=0.3.0",
]

